name: Auto Update France JSON

on:
  schedule:
    - cron: '0 */2 * * *'  # كل ساعتين
  workflow_dispatch:       # تشغيل يدوي من GitHub لو حبيت

jobs:
  update-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run script to fetch data
        run: python scripts/fetch_france.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "bot@example.com"
          git add france.json
          git commit -m "Auto update france.json"
          git push
