name: Auto Update France JSON

on:
  schedule:
    - cron: '0 */2 * * *'  # كل ساعتين
  workflow_dispatch:

jobs:
  update-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run script to fetch data
        run: python scripts/fetch_france.py

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update france.json
          file_pattern: france.json
          branch: main
